Hw18
cheslav84/A-Level pull request #16
Opened 2023-01-10 18:39 UTC by cheslav84

2023-01-13 22:55 UTC, Fabolo12 requested changes

2023-01-13 22:55 UTC, Fabolo12 commented on src/main/resources/car.xsd
> +<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
А ты заморочился :)

2023-01-13 22:55 UTC, Fabolo12 commented on src/main/java/com/havryliuk/Main.java
> +        String xmlFileName = "src/main/resources/car.xml";
Файл читается неверно

2023-01-13 22:55 UTC, Fabolo12 commented on src/main/java/com/havryliuk/util/CarJsonBuilder.java
> +            JSONArray jsonArr = new JSONArray(jsonObj.get(CAR).toString());
Задание про потоки что мы проходили на лекции

2023-01-14 17:49 UTC, cheslav84 commented on src/main/resources/car.xsd
> +<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
Так) хотілось зробити валідну XML-ну)

2023-01-14 20:54 UTC, cheslav84 commented on src/main/java/com/havryliuk/Main.java
> +        String xmlFileName = "src/main/resources/car.xml";
Виправив. Тут залишив DOM parser

2023-01-14 20:54 UTC, cheslav84 commented on src/main/java/com/havryliuk/util/CarJsonBuilder.java
> +            JSONArray jsonArr = new JSONArray(jsonObj.get(CAR).toString());
Виправив.

2023-01-15 19:57 UTC, Fabolo12 approved these changes

2023-01-20 19:55 UTC, closed without merging