Hw6: LJ3-130
cheslav84/A-Level pull request #4
Opened 2022-11-09 14:07 UTC by cheslav84

2022-11-10 21:13 UTC, Fabolo12 requested changes

2022-11-10 21:13 UTC, Fabolo12 commented on src/main/java/com/havryliuk/service/CarService.java
> +    public static Car create(){
Не статика

2022-11-10 21:13 UTC, Fabolo12 commented on src/main/java/com/havryliuk/service/CarService.java
> +    enum CarManufacturer{
Лучше вынести отдельным файлом

2022-11-11 20:04 UTC, cheslav84 commented on src/main/java/com/havryliuk/service/CarService.java
> +    public static Car create(){
Done.

2022-11-11 20:04 UTC, cheslav84 commented on src/main/java/com/havryliuk/service/CarService.java
> +    enum CarManufacturer{
Done.

2022-11-11 23:12 UTC, Fabolo12 approved these changes

2022-11-11 23:12 UTC, Fabolo12 commented on src/main/java/com/havryliuk/service/CarEngine.java
> +        return CarEngine.values()[new Random().nextInt(0, 3)];
3 это хардкор. В лекции есть пример как динамично искать случайное значение

2022-11-12 10:20 UTC, merged

2022-11-12 10:21 UTC, cheslav84 commented on src/main/java/com/havryliuk/service/CarEngine.java
> +        return CarEngine.values()[new Random().nextInt(0, 3)];
В 7му домашку так і зроблю. Це робив ще до лекції, і не хотів чіпати)